version: '3'
services:
  gateway:
    build: .
    image: brandonkervin/gateway
    container_name: gateway
    ports:
      - "80:80"
    environment:
      - PORT_NUMBER=80
      - OKTA_GATEWAY_CLIENT_ID=${OKTA_GATEWAY_CLIENT_ID}
      - OKTA_GATEWAY_CLIENT_SECRET=${OKTA_GATEWAY_CLIENT_SECRET}
      - OKTA_DEV_BASE_URI=${OKTA_DEV_BASE_URI}
    command: java -jar app.jar
    networks: 
      - gateway-net

networks: 
  gateway-net:
    driver: bridge